### ISSUE TITLE
brick_simple:{add,set,replace} APIs do not return the server-side timstamp for success

### ISSUE THREAD

**Issue by norton** [hibari/gdss-client#2]
These APIs only return 'ok' on success but some applications want/need the server-side created timestamp value to be returned as well.  To keep backwards compatibility, a new flag could be added to enable this feature.

**Comment by tatsuya6502** [comment]
I found that multi-node admin server can't be bootstrapped (https://github.com/hibari/gdss-admin/issues/8).

`brick_admin` and `brick_sb` modules rely on `brick_squorum` (simple quorum) client, and the quorum scheme doesn't work with server side timestamp. In squorum, each bricks are configured as standalone role so they will assign different timespamp for a key-value and cause a `quorum_error`.

To avoid this, `brick_squorum:set/6` and `brick_squorum:setmulti/2` should explicitly assign timestamp at client (admin server) side.

**Comment by tatsuya6502** [comment]
> To avoid this, `brick_squorum:set/6` and `brick_squorum:setmulti/2` should explicitly assign timestamp at client (admin server) side.

Updated but not tested. I'll try to run 3-node admin server config later tonight or early tomorrow.
https://github.com/hibari/gdss-admin/commit/a8fc2ed9bc2d358e3b3e1299d42a1e608488662d

**Comment by tatsuya6502** [comment]
I found that QuickCheck no longer fails with `quorum_error`.

**Comment by tatsuya6502** [comment]
There is one place that `brick_admin` directly adds a key-value to the quorum nodes. I updated it to use the same client-side timestamp. (Perhaps this should utilize `squorum:set/6`, but I fixed in place for now.)

Commits: https://github.com/hibari/gdss-admin/commit/1ec1391e35e0ceed2c68be0c470e2a73129db494, https://github.com/hibari/gdss-admin/commit/f7747e2680d6a459321d56d61ec73ddd7b573a0e

**Comment by tatsuya6502** [comment]
OK. I verified that it no longer fails to bootstrap 3-node admin server. Closing this issue.

```sh
[clus@hibaribench ~]$ grep ADMIN hibari.config 
ADMIN_NODES=(hibari1 hibari2 hibari3)
[clus@hibaribench ~]$ ./clus/priv/clus-hibari.sh bootstrap hibari hibari.config
ok
hibari@hibari1 => hibari@hibari1 hibari@hibari2 hibari@hibari3 hibari@hibari4 hibari@hibari5 hibari@hibari6
[clus@hibaribench ~]$ ./clus/priv/clus-hibari.sh ping hibari hibari.config
```
